<a href="https://colab.research.google.com/github/naitiksaxena/2ANN-Project/blob/main/2ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import keras
import tensorflow as tf
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
dataset = pd.read_csv("DOC-20260914-WA0012.csv")

In [ ]:
dataset

,hours_studied,attendance_percentage,assignments_completed,previous_exam_score,sleep_hours,extracurricular_hours,tutoring_sessions,parental_support_score,screen_time_hours,motivation_level,class_participation_score,final_marks
0,3.75,75.95,18,76.66,5.33,0.88,5,7,6.68,7,4,88.45
1,9.51,73.96,4,38.37,5.25,0.72,5,3,4.47,2,9,75.93
2,7.32,51.28,7,70.08,8.52,1.27,6,4,0.25,9,2,86.61
3,5.99,67.06,6,47.97,5.52,4.57,4,9,3.69,3,5,69.34
4,1.56,69.01,13,86.29,9.37,0.57,6,4,3.70,2,2,83.52
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,6.68,93.26,15,33.37,4.81,4.94,0,7,1.77,7,10,83.85
1496,6.19,57.86,18,63.85,5.89,4.41,2,10,2.62,2,3,85.08
1497,4.63,65.49,0,31.03,6.91,1.97,7,1,1.74,3,7,58.06
1498,3.80,64.50,2,94.48,6.87,3.43,7,1,3.13,8,7,86.90
1499,8.63,93.57,2,98.33,6.83,2.08,2,7,4.48,9,1,100.00

In [ ]:

X = dataset.drop(columns=["final_marks"])
y = dataset["final_marks"]

In [ ]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state=123)

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(units=11, kernel_initializer='uniform', activation='relu', input_dim=11))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
model.add(Dense(units=4, kernel_initializer='uniform', activation='relu'))

In [ ]:
model.add(Dense(units=1, kernel_initializer='uniform', activation='linear'))

In [ ]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [ ]:
model.fit(train_X, train_y, epochs=50, batch_size=32, validation_split=0.1)

Epoch 1/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7302.2153 - val_loss: 7311.9355
Epoch 2/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7268.3755 - val_loss: 7222.0527
Epoch 3/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7006.0923 - val_loss: 6657.5879
Epoch 4/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5877.1450 - val_loss: 4765.0947
Epoch 5/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3205.4927 - val_loss: 1514.3167
Epoch 6/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 536.2216 - val_loss: 88.9392
Epoch 7/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 100.4743 - val_loss: 85.4348
Epoch 8/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 92.9046 - val_loss: 86.8493
Epoch 9/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 92.0119 - val_loss: 85.1025
Epoch 10/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 90.8648 - val_loss: 84.8583
Epoch 11/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 89.7611 - val_loss: 82.4367
Epoch 12/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 88.5621 - val_loss: 82.3270
Epoch 13/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 87.2949 - val_loss: 81.5057
Epoch 14/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 86.2307 - val_loss: 79.9094
Epoch 15/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 85.2318 - val_loss: 80.7320
Epoch 16/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 83.5898 - val_loss: 78.1130
Epoch 17/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 82.3421 - val_loss: 78.1312
Epoch 18/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.0997 - val_loss: 76.1753
Epoch 19/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 79.6930 - val_loss: 75.3707
Epoch 20/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.5786 - val_loss: 73.7189
Epoch 21/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 77.3591 - val_loss: 73.6547
Epoch 22/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 75.8016 - val_loss: 72.9979
Epoch 23/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 74.4358 - val_loss: 71.2721
Epoch 24/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 73.1980 - val_loss: 70.7673
Epoch 25/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 72.0185 - val_loss: 70.3529
Epoch 26/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.5868 - val_loss: 68.7541
Epoch 27/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 69.3091 - val_loss: 68.0990
Epoch 28/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68.0159 - val_loss: 66.8693
Epoch 29/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 66.8824 - val_loss: 65.4594
Epoch 30/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 65.8055 - val_loss: 67.8776
Epoch 31/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 64.9349 - val_loss: 63.3287
Epoch 32/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 63.5052 - val_loss: 62.3188
Epoch 33/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 61.8669 - val_loss: 62.6660
Epoch 34/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 60.9416 - val_loss: 59.2246
Epoch 35/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 59.6449 - val_loss: 60.8039
Epoch 36/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 58.4287 - val_loss: 59.5339
Epoch 37/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 57.2726 - val_loss: 58.3050
Epoch 38/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 55.9537 - val_loss: 56.6245
Epoch 39/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 54.9916 - val_loss: 55.5068
Epoch 40/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 54.1498 - val_loss: 53.9801
Epoch 41/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 52.7755 - val_loss: 54.9920
Epoch 42/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 51.7621 - val_loss: 53.5664
Epoch 43/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50.6471 - val_loss: 52.0295
Epoch 44/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 49.7086 - val_loss: 50.9691
Epoch 45/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 48.7521 - val_loss: 49.4078
Epoch 46/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 47.8702 - val_loss: 49.6904
Epoch 47/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 46.8139 - val_loss: 48.8489
Epoch 48/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 45.7598 - val_loss: 47.9588
Epoch 49/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 44.8719 - val_loss: 49.4939
Epoch 50/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 43.9699 - val_loss: 45.5350

In [ ]:
mse = model.evaluate(test_X, test_y)
print(f'Test Mean Squared Error: {mse}')

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 45.5115
Test Mean Squared Error: 45.511505126953125

In [ ]:
predictions = model.predict(test_X)
predictions

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

array([[ 70.45254 ],
       [ 68.45649 ],
       [ 81.32621 ],
       [ 94.825035],
       [ 79.26237 ],
       [ 79.76059 ],
       [ 78.34312 ],
       [ 77.28751 ],
       [ 96.977776],
       [ 88.30219 ],
       [ 80.618515],
       [ 79.95445 ],
       [102.02445 ],
       [ 75.542145],
       [ 83.16644 ],
       [ 84.62651 ],
       [ 81.07105 ],
       [ 73.16461 ],
       [ 95.05158 ],
       [ 80.65157 ],
       [ 73.93366 ],
       [ 90.66475 ],
       [ 83.42038 ],
       [ 69.884285],
       [ 83.69308 ],
       [ 71.67083 ],
       [105.971275],
       [ 74.02567 ],
       [ 65.342674],
       [ 76.60706 ],
       [ 79.45807 ],
       [109.36342 ],
       [ 79.32128 ],
       [116.07021 ],
       [ 91.10937 ],
       [ 79.06507 ],
       [ 86.79066 ],
       [ 83.70505 ],
       [ 83.525345],
       [ 84.7582  ],
       [ 82.157906],
       [ 86.36621 ],
       [ 80.21431 ],
       [ 79.2432  ],
       [ 56.15586 ],
       [ 77.30169 ],
       [ 94.82399 ],
       [ 86.849174],
       [ 73.6502  ],
       [ 97.80144 ],
       [ 75.46572 ],
       [ 85.444496],
       [ 79.18724 ],
       [ 79.762924],
       [ 91.3935  ],
       [ 73.1535  ],
       [ 81.43435 ],
       [ 71.16648 ],
       [ 89.113106],
       [ 87.01159 ],
       [ 80.77282 ],
       [ 67.577866],
       [ 77.14874 ],
       [ 75.00504 ],
       [ 71.061485],
       [ 87.92719 ],
       [ 83.13325 ],
       [ 86.82198 ],
       [102.49363 ],
       [ 96.583336],
       [ 68.88938 ],
       [ 91.35965 ],
       [ 77.856255],
       [ 88.5313  ],
       [100.15368 ],
       [ 69.01564 ],
       [105.32908 ],
       [ 76.93665 ],
       [ 93.578476],
       [ 84.55199 ],
       [ 79.15653 ],
       [ 81.03814 ],
       [ 76.81732 ],
       [108.86652 ],
       [ 83.04225 ],
       [ 95.67261 ],
       [ 99.17489 ],
       [ 86.6363  ],
       [ 91.42513 ],
       [ 90.747246],
       [ 83.06538 ],
       [ 87.302155],
       [ 86.83251 ],
       [ 84.95153 ],
       [ 92.71702 ],
       [ 75.51408 ],
       [ 88.37536 ],
       [ 83.420525],
       [ 70.11791 ],
       [ 72.35973 ],
       [ 63.329918],
       [ 90.44757 ],
       [ 94.037254],
       [ 91.56256 ],
       [ 92.864204],
       [105.82836 ],
       [ 72.454895],
       [ 62.36486 ],
       [ 74.89103 ],
       [ 90.98825 ],
       [ 87.427444],
       [ 69.604866],
       [ 94.67628 ],
       [ 78.25434 ],
       [ 71.98814 ],
       [ 82.72176 ],
       [ 86.53123 ],
       [ 85.500175],
       [ 88.32601 ],
       [ 88.21531 ],
       [ 85.36648 ],
       [ 87.31922 ],
       [ 94.37815 ],
       [ 68.87621 ],
       [ 69.02163 ],
       [ 96.711914],
       [ 80.94599 ],
       [110.189735],
       [ 77.93169 ],
       [ 74.62755 ],
       [ 78.65314 ],
       [ 71.21372 ],
       [ 98.539635],
       [ 63.202908],
       [ 76.40276 ],
       [ 96.02893 ],
       [ 99.60499 ],
       [ 74.35171 ],
       [ 86.64274 ],
       [ 71.5736  ],
       [ 76.622856],
       [ 98.14811 ],
       [ 73.73905 ],
       [ 68.51652 ],
       [ 98.32752 ],
       [ 82.81562 ],
       [ 79.72953 ],
       [ 96.099945],
       [ 82.942696],
       [ 92.07233 ],
       [ 83.33899 ],
       [ 74.54595 ],
       [ 95.94743 ],
       [ 71.90277 ],
       [ 77.54392 ],
       [ 97.178764],
       [ 76.82162 ],
       [ 93.39788 ],
       [ 81.393456],
       [ 84.46697 ],
       [ 95.438995],
       [101.85263 ],
       [ 95.07791 ],
       [ 87.218895],
       [102.583275],
       [ 72.19988 ],
       [ 91.38822 ],
       [ 97.29583 ],
       [ 73.47161 ],
       [ 79.77795 ],
       [ 93.215904],
       [ 75.74011 ],
       [ 93.65715 ],
       [ 78.58938 ],
       [ 94.45632 ],
       [ 84.55052 ],
       [ 76.551476],
       [ 79.74305 ],
       [ 82.88147 ],
       [ 73.65388 ],
       [ 82.74355 ],
       [ 72.7315  ],
       [ 76.96779 ],
       [ 77.74247 ],
       [ 94.66424 ],
       [ 90.88526 ],
       [ 85.095146],
       [ 92.47033 ],
       [ 93.45802 ],
       [101.08553 ],
       [ 62.12865 ],
       [ 82.44239 ],
       [ 68.72936 ],
       [ 86.090195],
       [ 71.774345],
       [ 78.05524 ],
       [ 78.486244],
       [ 84.930466],
       [ 91.292564],
       [ 99.2387  ],
       [ 90.10337 ],
       [ 77.67625 ],
       [ 75.1995  ],
       [ 88.575584],
       [ 69.15806 ],
       [ 72.09974 ],
       [ 90.62595 ],
       [ 89.33048 ],
       [ 81.563   ],
       [ 84.87889 ],
       [ 96.58207 ],
       [101.470184],
       [ 93.43102 ],
       [ 84.93377 ],
       [ 75.20896 ],
       [ 87.8334  ],
       [ 83.80787 ],
       [ 84.36554 ],
       [ 76.0693  ],
       [ 64.66331 ],
       [ 95.07835 ],
       [ 86.977684],
       [ 82.865906],
       [ 98.875885],
       [ 77.50454 ],
       [ 75.67306 ],
       [107.295235],
       [ 82.52554 ],
       [106.36668 ],
       [ 76.56049 ],
       [ 91.92161 ],
       [ 85.87226 ],
       [ 98.71848 ],
       [ 66.45668 ],
       [ 92.07257 ],
       [ 73.15664 ],
       [ 84.55932 ],
       [ 95.348854],
       [ 82.37585 ],
       [ 71.15639 ],
       [ 70.75082 ],
       [ 78.25149 ],
       [ 75.67983 ],
       [103.593124],
       [101.14676 ],
       [ 94.04954 ],
       [ 89.256905],
       [ 76.38837 ],
       [109.706535],
       [ 68.96248 ],
       [ 67.0939  ],
       [ 72.51399 ],
       [ 80.0671  ],
       [ 80.47664 ],
       [ 85.37805 ],
       [ 96.70635 ],
       [ 81.56042 ],
       [ 82.360634],
       [ 75.7266  ],
       [ 87.638695],
       [ 89.18403 ],
       [ 78.466576],
       [ 68.15614 ],
       [ 73.15566 ],
       [ 78.64991 ],
       [ 88.5599  ],
       [ 92.18095 ],
       [ 93.822075],
       [ 90.7078  ],
       [ 78.93988 ],
       [ 75.30067 ],
       [ 87.91873 ],
       [ 65.121956],
       [ 81.43572 ],
       [104.65727 ],
       [ 70.24387 ],
       [ 77.29834 ],
       [ 94.31429 ],
       [ 95.329056],
       [ 80.59661 ],
       [ 56.260902],
       [ 75.05535 ],
       [ 79.54065 ],
       [102.70716 ],
       [100.94631 ],
       [ 71.09144 ],
       [ 84.89628 ],
       [ 85.2774  ],
       [ 94.95356 ],
       [ 85.480965],
       [ 80.65264 ],
       [ 88.04069 ],
       [ 70.12    ],
       [ 84.830505],
       [105.24757 ],
       [ 64.44984 ],
       [ 93.80208 ],
       [ 62.23596 ],
       [ 99.38033 ],
       [ 75.24648 ],
       [ 89.31581 ],
       [ 69.5772  ],
       [ 83.102776],
       [ 91.60634 ],
       [ 99.13882 ],
       [ 97.30119 ],
       [ 76.92332 ],
       [ 93.314445],
       [ 76.79013 ],
       [ 93.32891 ],
       [ 74.15685 ],
       [ 82.613945],
       [ 84.515785],
       [ 80.17881 ],
       [ 85.79973 ],
       [ 96.09207 ],
       [ 83.86648 ],
       [ 81.494576],
       [ 93.68397 ],
       [ 85.89411 ],
       [ 86.87365 ],
       [ 77.722984],
       [ 66.5669  ],
       [ 95.42303 ],
       [ 67.24834 ],
       [ 66.958954],
       [ 94.46496 ],
       [ 66.19526 ],
       [ 80.881935],
       [ 97.603935],
       [ 74.57135 ],
       [ 97.457344],
       [100.93709 ],
       [ 86.44903 ],
       [ 79.26302 ],
       [ 87.55835 ],
       [ 62.22997 ],
       [ 94.52352 ],
       [110.623886],
       [ 81.38818 ],
       [ 80.34617 ],
       [ 94.37832 ],
       [ 86.47558 ],
       [ 62.216755],
       [ 79.86608 ],
       [ 75.632454],
       [ 94.37437 ],
       [ 98.85141 ],
       [ 91.166534],
       [ 80.09231 ],
       [ 87.65281 ],
       [ 59.199055],
       [ 95.096825],
       [ 61.05418 ],
       [ 87.36293 ],
       [ 95.166466],
       [ 67.561516],
       [ 82.50303 ],
       [ 76.15783 ],
       [105.77452 ],
       [116.69274 ],
       [ 78.26644 ],
       [ 70.62045 ],
       [ 72.06977 ],
       [ 81.0138  ],
       [ 87.638336],
       [ 88.16921 ],
       [ 57.5385  ],
       [ 91.252495],
       [ 84.16147 ],
       [ 67.82328 ],
       [ 69.740005],
       [ 84.53382 ],
       [ 60.354877],
       [ 69.634544],
       [ 77.21375 ],
       [ 82.94352 ],
       [ 69.719215],
       [ 86.484825],
       [ 92.624245],
       [ 87.255035],
       [ 98.09873 ],
       [ 69.77189 ],
       [ 73.67377 ],
       [ 80.61555 ],
       [101.27793 ],
       [ 62.042492],
       [ 76.365486],
       [ 82.20948 ],
       [ 98.09171 ],
       [ 82.926   ],
       [ 76.75727 ],
       [ 87.110085],
       [ 89.125496],
       [ 84.65767 ],
       [ 93.61556 ],
       [ 93.727234],
       [ 61.93709 ],
       [ 76.26841 ],
       [ 77.50773 ],
       [100.31037 ],
       [ 66.14636 ],
       [ 82.74003 ],
       [ 92.66291 ],
       [ 85.43663 ],
       [ 92.31337 ],
       [ 94.52501 ],
       [106.20837 ],
       [ 96.17274 ],
       [ 86.28128 ],
       [ 81.62405 ],
       [ 61.54617 ],
       [ 77.48007 ],
       [ 92.23487 ],
       [ 75.18989 ],
       [ 93.02245 ],
       [ 75.704414],
       [ 75.348   ],
       [ 94.84114 ],
       [ 87.79325 ],
       [ 93.52888 ],
       [101.10359 ],
       [ 87.28797 ],
       [ 69.512566],
       [ 95.1567  ],
       [ 74.65828 ],
       [100.69977 ],
       [ 70.23985 ],
       [ 88.54156 ],
       [ 69.95577 ],
       [ 86.010704],
       [ 76.15168 ],
       [ 83.46514 ],
       [103.54555 ],
       [ 91.0902  ],
       [ 83.80453 ],
       [105.09298 ],
       [ 69.91309 ],
       [ 84.26716 ],
       [ 73.961754],
       [ 92.70782 ],
       [ 70.08602 ],
       [ 65.08547 ],
       [ 88.25115 ],
       [ 57.061962],
       [ 96.62595 ],
       [ 74.393486],
       [ 62.413754],
       [ 67.617546],
       [ 80.26791 ]], dtype=float32)

In [ ]:
comparison = pd.DataFrame({"Actual": test_y.values, "Predicted": predictions.flatten()})
comparison.head(10)

   Actual  Predicted
0   81.22  70.452538
1   66.29  68.456490
2   89.41  81.326210
3   99.16  94.825035
4   82.50  79.262367
5   74.61  79.760590
6   85.60  78.343117
7   79.33  77.287514
8   86.57  96.977776
9   88.45  88.302193